version: '3.8'
services:
  mongo:
    image: mongo:6.0
    container_name: polyspack-mongo-test
    ports:
      - '27017:27017'
    volumes:
      - mongo_data_test:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  mongo_data_test: